export const authConstants = {


  LOGIN_OTP_REQUEST: "LOGIN_OTP_REQUEST",
  LOGIN_OTP_SUCCESS: "LOGIN_OTP_SUCCESS",
  LOGIN_OTP_FAILURE: "LOGIN_OTP_FAILURE",


  LOGIN_OTP_VERIFIY_REQUEST: "LOGIN_OTP_VERIFIY_REQUEST",
  LOGIN_OTP_VERIFIY_SUCCESS: "LOGIN_OTP_VERIFIY_SUCCESS",
  LOGIN_OTP_VERIFIY_FAILURE: "LOGIN_OTP_VERIFIY_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};



export const pageConstants = {
  GET_ALL_PAGE_REQUEST: "GET_ALL_PAGE_REQUEST",
  GET_ALL_PAGE_SUCCESS: "GET_ALL_PAGE_SUCCESS",
  GET_ALL_PAGE_FAILURE: "GET_ALL_PAGE_FAILURE",

  CREATE_PAGE_ACTION_REQUEST: "CREATE_PAGE_ACTION_REQUEST",
  CREATE_PAGE_ACTION_SUCCESS: "CREATE_PAGE_ACTION_SUCCESS",
  CREATE_PAGE_ACTION_FAILURE: "CREATE_PAGE_ACTION_FAILURE",


  UPDATE_PAGE_ACTION_REQUEST: "UPDATE_PAGE_ACTION_REQUEST",
  UPDATE_PAGE_ACTION_SUCCESS: "UPDATE_PAGE_ACTION_SUCCESS",
  UPDATE_PAGE_ACTION_FAILURE: "UPDATE_PAGE_ACTION_FAILURE",

  DELETE_PAGE_ACTION_REQUEST: "DELETE_PAGE_ACTION_REQUEST",
  DELETE_PAGE_ACTION_SUCCESS: "DELETE_PAGE_ACTION_SUCCESS",
  DELETE_PAGE_ACTION_FAILURE: "DELETE_PAGE_ACTION_FAILURE",

  GET_PAGE_BY_URL_REQUEST: "GET_PAGE_BY_URL_REQUEST",
  GET_PAGE_BY_URL_SUCCESS: "GET_PAGE_BY_URL_SUCCESS",
  GET_PAGE_BY_URL_FAILURE: "GET_PAGE_BY_URL_FAILURE",

};
